development:
  host: '127.0.0.1'
  port: 9042
  keyspace: smartcitizen_development
  max_retries: 3
  retry_delay: 0.5
  newrelic: false

test:
  host: '127.0.0.1'
  port: 9042
  keyspace: smartcitizen_testing
  max_retries: 3
  retry_delay: 0.5
  newrelic: false

production:
  hosts:
    - 'cass1.smartcitizen.biz'
    - 'cass2.smartcitizen.biz'
    - 'cass3.smartcitizen.biz'
  port: 9042
  keyspace: smartcitizen_production
  username: 'myappuser'
  password: 'password1'
  max_retries: 3
  retry_delay: 0.5
  newrelic: true
  replication:
    class: SimpleStrategy
    replication_factor: 1
# replication:
#   class: NetworkTopologyStrategy
#   datacenter1: 3
#   datacenter2: 2
# durable_writes: false
